// Catálogo de emojis para el selector. Sin dependencias externas: cada entrada
// es "<emoji> <palabras clave en español>" para que la búsqueda sea un simple
// match de substring. Curado, no exhaustivo: lo que se usa de verdad al hablar
// de partidas, más las categorías clásicas.

export type EmojiCategory = {
  id: string;
  label: string;
  icon: string;
  entries: string[];
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "juegos",
    label: "Juegos",
    icon: "🎲",
    entries: [
      "🎲 dado dados azar suerte juego",
      "🃏 carta cartas comodin joker baraja",
      "🀄 mahjong ficha oriental",
      "♟️ peon ajedrez pieza estrategia",
      "🎯 diana objetivo puntería acierto",
      "🎮 mando videojuego consola",
      "🕹️ joystick arcade retro",
      "🎰 tragaperras maquina azar",
      "🧩 puzzle pieza rompecabezas encajar",
      "🏆 trofeo copa ganador campeon victoria",
      "🥇 oro primero medalla ganador",
      "🥈 plata segundo medalla",
      "🥉 bronce tercero medalla",
      "🏅 medalla premio",
      "👑 corona rey reina ganador mandar",
      "⚔️ espadas batalla lucha guerra conflicto",
      "🛡️ escudo defensa proteger",
      "🗡️ espada daga arma",
      "🏰 castillo fortaleza medieval reino",
      "🧙 mago hechicero magia fantasia",
      "🧝 elfo fantasia",
      "🧟 zombi muerto viviente terror",
      "🐉 dragon fantasia bestia",
      "👾 marciano alien bicho",
      "🤖 robot autómata maquina",
      "🚀 cohete espacio nave despegue",
      "🛸 ovni platillo alien",
      "🗺️ mapa territorio exploracion aventura",
      "🧭 brujula rumbo norte",
      "⏳ reloj arena tiempo espera turno",
      "⏱️ cronometro tiempo rapido",
      "🎪 carpa circo evento",
      "🎭 mascaras teatro rol interpretar",
      "🪄 varita magia truco",
      "💎 diamante gema tesoro valioso",
      "💰 dinero saco monedas riqueza",
      "🪙 moneda dinero pagar",
      "🔮 bola cristal adivinar futuro",
      "📖 libro reglas manual leer",
      "🧠 cerebro pensar listo estrategia",
      "💡 idea bombilla ocurrencia",
      "🔥 fuego arde racha genial",
      "💥 explosion boom choque",
      "🎉 fiesta celebracion confeti",
      "🎊 confeti fiesta celebrar",
    ],
  },
  {
    id: "caras",
    label: "Caras",
    icon: "😀",
    entries: [
      "😀 sonrisa feliz contento alegre",
      "😃 sonrisa alegre feliz",
      "😄 risa feliz alegre contento",
      "😁 sonrisa dientes feliz",
      "😆 risa carcajada gracia",
      "😅 risa sudor nervios alivio",
      "🤣 carcajada suelo risa gracia",
      "😂 llorar risa gracia lol",
      "🙂 sonrisa leve contento",
      "🙃 cara reves ironia sarcasmo",
      "😉 guiño complicidad",
      "😊 sonrisa timida contento agradecido",
      "😇 angel inocente santo",
      "🥰 enamorado corazones cariño",
      "😍 enamorado ojos corazon me encanta",
      "🤩 flipando estrellas alucinar",
      "😘 beso cariño",
      "😋 rico sabroso lengua",
      "😛 lengua broma",
      "🤪 loco chalado gracia",
      "🤨 ceja duda sospecha",
      "🧐 monoculo analizar examinar",
      "🤓 empollon gafas friki nerd",
      "😎 gafas sol guay chulo",
      "🥳 fiesta celebrar cumpleaños",
      "😏 picardia listillo sonrisa",
      "😒 harto desdén aburrido",
      "😞 decepcion triste pena",
      "😔 pena triste bajon",
      "😟 preocupado inquieto",
      "😕 confuso duda",
      "🙁 triste disgusto",
      "😣 esfuerzo agobio",
      "😖 frustracion agobio",
      "😫 cansado harto agotado",
      "😩 agotado harto queja",
      "🥺 suplica pena porfa ojitos",
      "😢 llorar triste lagrima",
      "😭 llorar mucho drama pena",
      "😤 enfado resoplar orgullo",
      "😠 enfadado cabreo",
      "😡 furioso cabreado rabia",
      "🤬 palabrota insulto cabreo",
      "🤯 explota cabeza flipar alucinar",
      "😳 sonrojo vergüenza sorpresa",
      "🥵 calor sofoco",
      "🥶 frio helado",
      "😱 grito susto miedo panico",
      "😨 miedo susto",
      "😰 angustia sudor nervios",
      "😥 alivio pena",
      "😓 sudor agobio",
      "🤔 pensar duda mmm reflexionar",
      "🤭 ups risa tapar boca",
      "🤫 silencio callar secreto",
      "🤥 mentira nariz",
      "😶 sin palabras mudo",
      "😐 neutral serio indiferente",
      "😑 inexpresivo harto",
      "😬 mueca tension incomodo",
      "🙄 ojos arriba paso desdén",
      "😴 dormir sueño aburrido",
      "🤤 babear antojo",
      "🤢 asco nauseas",
      "🤮 vomito asco",
      "🤧 estornudo resfriado",
      "🤒 enfermo fiebre",
      "🤕 herido venda",
      "🥴 mareado grogui",
      "😵 mareado ko aturdido",
      "🤠 vaquero sombrero",
      "🥸 disfraz bigote",
      "😈 diablo travieso malvado",
      "👻 fantasma susto broma",
      "💀 calavera muerto fin",
      "🤡 payaso broma ridiculo",
      "👽 alien marciano",
      "🎃 calabaza halloween",
      "😺 gato feliz",
      "😻 gato enamorado",
    ],
  },
  {
    id: "gestos",
    label: "Gestos",
    icon: "👍",
    entries: [
      "👍 ok bien pulgar arriba vale genial",
      "👎 mal no pulgar abajo",
      "👏 aplauso bravo enhorabuena",
      "🙌 manos arriba celebrar bien",
      "🤝 acuerdo trato mano apreton",
      "👋 hola adios saludo",
      "✌️ paz victoria",
      "🤞 suerte dedos cruzados",
      "🤙 llamame guay",
      "👌 perfecto ok vale",
      "🤌 italiano gesto que dices",
      "💪 fuerza musculo animo",
      "🙏 gracias porfavor rezar suplica",
      "🫶 corazon manos cariño",
      "🤲 manos ofrecer",
      "👇 abajo señalar",
      "👉 derecha señalar",
      "👈 izquierda señalar",
      "☝️ arriba atencion",
      "✋ alto mano parar",
      "🖐️ mano abierta",
      "🫡 saludo militar a la orden",
      "🤷 ni idea encogerse hombros",
      "🤦 facepalm vergüenza ajena",
      "🙋 levantar mano yo apuntarse",
      "🙆 vale ok gesto",
      "🙅 no negacion prohibido",
      "💁 informacion actitud",
      "🕺 bailar fiesta",
      "💃 bailar fiesta flamenca",
      "🧑‍🤝‍🧑 amigos grupo gente",
      "👨‍👩‍👧 familia",
      "🫂 abrazo consuelo",
      "👀 ojos mirar atencion vigilando",
      "🧏 escuchar sordo",
      "🤰 embarazo",
      "🧑‍🍳 cocinero chef",
    ],
  },
  {
    id: "simbolos",
    label: "Símbolos",
    icon: "❤️",
    entries: [
      "❤️ corazon amor rojo",
      "🧡 corazon naranja",
      "💛 corazon amarillo",
      "💚 corazon verde",
      "💙 corazon azul",
      "💜 corazon morado",
      "🖤 corazon negro",
      "🤍 corazon blanco",
      "💔 corazon roto pena",
      "💕 corazones amor",
      "💖 corazon brillante amor",
      "❣️ corazon exclamacion",
      "✨ brillo magia genial nuevo",
      "⭐ estrella favorito",
      "🌟 estrella brillante destacar",
      "💫 mareo estrella",
      "💯 cien perfecto total",
      "✅ ok hecho correcto si",
      "☑️ marcado check",
      "❌ no mal error incorrecto",
      "⛔ prohibido stop",
      "⚠️ aviso cuidado peligro",
      "❓ pregunta duda",
      "❗ atencion importante",
      "🔴 circulo rojo",
      "🟠 circulo naranja",
      "🟡 circulo amarillo",
      "🟢 circulo verde disponible",
      "🔵 circulo azul",
      "🟣 circulo morado",
      "⚫ circulo negro",
      "⚪ circulo blanco",
      "🔺 triangulo rojo subir",
      "🔻 triangulo bajar",
      "♻️ reciclar reutilizar",
      "🔁 repetir bucle otra vez",
      "🔀 aleatorio mezclar barajar",
      "➕ mas sumar añadir",
      "➖ menos restar quitar",
      "🆕 nuevo",
      "🆗 ok vale",
      "🔝 top arriba mejor",
      "©️ copyright",
      "🇪🇸 españa bandera",
    ],
  },
  {
    id: "comida",
    label: "Comida",
    icon: "🍕",
    entries: [
      "🍕 pizza cena",
      "🍔 hamburguesa",
      "🍟 patatas fritas",
      "🌮 taco mexicano",
      "🌯 burrito",
      "🥪 sandwich bocadillo",
      "🍿 palomitas peli",
      "🥨 pretzel",
      "🧀 queso",
      "🥐 croissant desayuno",
      "🍞 pan",
      "🍝 pasta espagueti",
      "🍣 sushi",
      "🍜 ramen sopa",
      "🥗 ensalada sano",
      "🍫 chocolate dulce",
      "🍪 galleta dulce",
      "🍰 tarta pastel dulce",
      "🎂 cumpleaños tarta celebrar",
      "🍦 helado",
      "🍩 donut dulce",
      "🍺 cerveza birra quedada",
      "🍻 cervezas brindis quedada",
      "🍷 vino copa",
      "🥂 brindis celebrar copas",
      "🍾 champan celebrar descorchar",
      "🍹 cocktail copa fiesta",
      "🥤 refresco vaso",
      "☕ cafe desayuno",
      "🫖 te infusion",
      "🧉 mate infusion",
      "🍇 uvas fruta",
      "🍓 fresa fruta",
      "🍉 sandia fruta",
      "🍎 manzana fruta",
      "🍌 platano fruta",
      "🥕 zanahoria verdura",
      "🌶️ picante chile",
      "🥑 aguacate",
      "🍽️ plato cubiertos comer cena",
    ],
  },
  {
    id: "naturaleza",
    label: "Animales",
    icon: "🐶",
    entries: [
      "🐶 perro can",
      "🐱 gato minino",
      "🐭 raton",
      "🐹 hamster",
      "🐰 conejo",
      "🦊 zorro",
      "🐻 oso",
      "🐼 panda",
      "🐨 koala",
      "🐯 tigre",
      "🦁 leon",
      "🐮 vaca",
      "🐷 cerdo",
      "🐸 rana",
      "🐵 mono",
      "🙈 mono ojos no ver vergüenza",
      "🐔 gallina pollo",
      "🐧 pinguino",
      "🦆 pato",
      "🦉 buho lechuza noche",
      "🦄 unicornio fantasia",
      "🐝 abeja",
      "🐞 mariquita",
      "🦋 mariposa",
      "🐢 tortuga lento",
      "🐍 serpiente",
      "🐙 pulpo",
      "🦀 cangrejo",
      "🐳 ballena",
      "🐬 delfin",
      "🐴 caballo",
      "🦖 dinosaurio trex",
      "🌵 cactus",
      "🌲 arbol pino bosque",
      "🌴 palmera playa",
      "🍀 trebol suerte",
      "🍁 hoja otoño",
      "🌸 flor cerezo",
      "🌻 girasol flor",
      "🌹 rosa flor",
      "🌈 arcoiris color",
      "☀️ sol dia buen tiempo",
      "🌙 luna noche",
      "⛅ nubes tiempo",
      "🌧️ lluvia",
      "⛈️ tormenta",
      "❄️ nieve frio copo",
      "⛄ muñeco nieve invierno",
      "🌊 ola mar playa",
      "🔆 brillo luz",
    ],
  },
  {
    id: "objetos",
    label: "Objetos",
    icon: "📅",
    entries: [
      "📅 calendario fecha dia quedada",
      "🗓️ calendario planificar agenda",
      "⏰ despertador hora alarma",
      "🕐 reloj hora",
      "📍 ubicacion sitio lugar chincheta",
      "🏠 casa hogar",
      "🏡 casa jardin",
      "🏢 oficina edificio",
      "🚗 coche llevar conducir",
      "🚌 autobus",
      "🚇 metro",
      "🚲 bici",
      "✈️ avion viaje",
      "🚂 tren",
      "⛵ barco velero",
      "🏖️ playa vacaciones",
      "⛰️ montaña",
      "🎁 regalo sorpresa",
      "🎈 globo fiesta",
      "🕯️ vela ambiente",
      "📱 movil telefono",
      "💻 portatil ordenador",
      "🖥️ ordenador pantalla",
      "📷 camara foto",
      "📸 foto flash",
      "🎥 video camara grabar",
      "📺 tele television",
      "🎧 auriculares musica",
      "🎵 nota musica",
      "🎶 musica notas",
      "🎤 micro cantar karaoke",
      "🔔 campana aviso notificacion",
      "📢 megafono aviso anuncio",
      "📣 megafono convocar animar",
      "✉️ sobre email carta",
      "📩 email mensaje",
      "📝 nota escribir apuntar comentario",
      "📌 chincheta fijar importante",
      "📊 grafico estadisticas datos",
      "📈 subir grafico mejorar",
      "📉 bajar grafico empeorar",
      "🔍 buscar lupa",
      "🔑 llave acceso",
      "🔒 candado privado cerrado",
      "🔓 abierto candado",
      "🧾 recibo cuenta ticket",
      "💳 tarjeta pagar",
      "🛒 carrito comprar",
      "📦 caja paquete juego",
      "🧹 limpiar escoba orden",
      "🔧 herramienta arreglar",
      "⚙️ ajustes engranaje configurar",
      "🖊️ boli escribir",
      "📚 libros biblioteca",
      "🔖 marcador guardar",
      "🧊 hielo cubito",
      "🪑 silla mesa sitio",
    ],
  },
];

export type ParsedEmoji = { char: string; keywords: string };

// "🎲 dado dados" -> { char: "🎲", keywords: "dado dados" }
export function parseEntry(entry: string): ParsedEmoji {
  const space = entry.indexOf(" ");
  if (space === -1) return { char: entry, keywords: "" };
  return { char: entry.slice(0, space), keywords: entry.slice(space + 1) };
}

const ALL_ENTRIES = EMOJI_CATEGORIES.flatMap((c) => c.entries);

// Búsqueda simple por substring sobre las palabras clave (sin acentos).
export function searchEmojis(query: string): ParsedEmoji[] {
  const q = query
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
  if (!q) return [];
  const seen = new Set<string>();
  const out: ParsedEmoji[] = [];
  for (const entry of ALL_ENTRIES) {
    const parsed = parseEntry(entry);
    const haystack = parsed.keywords
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "");
    if (haystack.includes(q) && !seen.has(parsed.char)) {
      seen.add(parsed.char);
      out.push(parsed);
    }
  }
  return out;
}
